import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillFacebook} from "react-icons/ai"
import Image from "next/legacy/image"
import mann2 from '../public/mann2.png'
import frontend from '../public/frontend.png'
import backend from '../public/backend.png'
import code from '../public/code.png'
import React, { Component, use } from 'react'
import { useState } from 'react'



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Mann Arora Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-gradient-to-bf from-white to bg-gray-100   -white px-10 ">
        <section className="h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-light'> Developed by Mann </h1>
            <ul className="flex items-center"> 
              <li className='cursor-pointer text-2xl'><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}/></li>
              <li>
                <a className=' bg-cyan-500 text-white px-4 py-2 rounded-md ml-8  font-bold'  href="https://www.linkedin.com/in/mann-arora-98a5b3219/">Contact Me</a>
              </li>
            </ul>
          </nav>

          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-md font-semibold'> Mann Arora </h2>
            <h3 className=' text-2xl font-medium'> Computer Science Student </h3>
            <p className=' text-md py-5 leading-8 text-gray-800 font-semibold text'> Studying a Bachelor of Computer Science and Finance at UNSW. Aspiring to be a Software Engineer. Connect with me Below!
            </p>
            <div className='text-xl flex justify-center gap-16 py-3 '>
              
              <a className=' bg-gradient-to-r from-cyan-600 to bg-sky-800 text-white px-4 py-2 rounded-md ml-8  font-bold'  href="https://www.linkedin.com/in/mann-arora-98a5b3219/">LinkedIn</a>
              
            </div>
            <div className=' relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 py-20  overflow-hidden'>
              <Image src={mann2} objectFit="cover" />
            </div>
          </div>
        </section>
        
        <section>
          <div >
             <h3 className='text-3xl font-medium text-center pb-5'>About Me!</h3>
             <p> As a <span className=' font-bold text-teal-700'>penultimate student</span> finishing off a <span className=' font-bold  text-teal-700'>Bachelor of Computer Science and Finance</span> , I have developed a strong passion in <span className=' font-bold  text-teal-700'>software engineering</span>. I enjoy creating and innovating within various software projects. By applying the skills I have developed, I am determined to create a strong impact in the field of technology. You can see my skillset below!</p>
          
          </div>

          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-gradient-to-t from-white to-cyan-100'>
              <Image src={frontend} width={100} height={100}/>
              <h3 className='text-lg font-bold pt-2 pb-10'> Front-End </h3>
              
          
              <p className=' text-gray-800 py-1  font-semibold'> JavaScript </p>
              <p className='text-gray-800 py-1 font-semibold'> React.js & Next.js</p>
              <p className='text-gray-800 py-1 font-semibold'> HTML & CSS </p>
              <p className='text-gray-800 py-1 font-semibold'> Tailwind and BootStrap</p>
            </div> 
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10  bg-gradient-to-t from-cyan-100 to-white'>
            <Image src={backend} width={100} height={100}/>
            <h3 className='text-lg font-bold pt-2 pb-10'> Back-End </h3>
        
            <p className='text-gray-800 py-1 font-semibold'> Java </p>
            <p className='text-gray-800 py-1 font-semibold'> Python </p>
            <p className='text-gray-800 py-1 font-semibold'> C </p>
            <p className='text-gray-800 py-1 font-semibold'> Data Structures and Algorithms </p>
            <p className='text-gray-800 py-1 font-semibold'> APIs </p>

          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10  bg-gradient-to-r from-cyan-100 to-white'>
            <Image src={code} width={100} height={100}/>
            <h3 className=' text-xl font-bold pt-2 pb-10'> Other Skills </h3>
        
            <p className='text-gray-800 py-1 font-semibold'> Github & Gitlab </p>
            <p className='text-gray-800 py-1 font-semibold'> R Programming (Data Analysis) </p>
            <p className='text-gray-800 py-1 font-semibold'> Object-Oriented Programming and Design Patterns </p>
            <p className='text-gray-800 py-1 font-semibold'> Agile Principles & SDLC </p>
            <p className='text-gray-800 py-1 font-semibold'> Writing effective unit and block tests </p>

          </div>
        </section>
        <section>
          <div className='pb-10'>
            <h3 className='text-3xl font-bold pt-2 pb-5 text-center'> My Goal </h3>
            <p > My goal is to work as a <span className=' text-cyan-700 font-bold'> software engineer </span>, helping businesses develop well maintained software. I aim to help companies thrive in their technological presence and shape the way digital presence produces success. Furthermore, I am hoping to learn and progress my knowledge and eventually become a full stack engineer. </p>
          </div>
          <div></div>
        </section>


      </main>
    </div>
  )
}
